SELECT * FROM SALES;
SELECT * FROM ACCOUNTS;
SELECT * FROM PRODUCTS;
SELECT * FROM CUSTOMER;
--총 판매액
SELECT SUM(AMOUNT) FROM SALES;
--제품별 판매금액

SELECT PROD_NAME, SUM(QUANTITY) 수량합 ,SUM(AMOUNT) 판매금액 FROM SALES S, PRODUCTS P
WHERE S.PROD_NO = S.PROD_NO
GROUP BY PROD_NAME;

SELECT CU_NAME,SUM(AMOUNT) 판매금액 FROM SALES S, CUSTOMER C
WHERE C.CUST_ID = S.CUST_ID;

SELECT CU_NAME, PROD_NAME ,SUM(QUANTITY) 수량합, SUM(AMOUNT) 판매금액합
FROM SALES S, CUSTOMER C, PRODUCTS P
WHERE C.CUST_ID = S.CUST_ID AND S.PROD_NO = P.PROD_NO
GROUP BY CU_NAME, PROD_NAME
ORDER BY CU_NAME;

--생월이 2월달인 고객
SELECT * FROM CUSTOMER;
SELECT CU_NAME , BIRTH FROM CUSTOMER
WHERE TO_CHAR(BIRTH, 'MM') = '02';  