SELECT CU_NAME, PAYMENT, sum(AMOUNT)
FROM CUSTOMER C, SALES S
WHERE C.CUST_ID = S.CUST_ID AND C.CUST_ID IN (SELECT CUST_ID
                                              FROM CUSTOMER
                                              WHERE ADDR NOT LIKE '%대전%')
GROUP BY CU_NAME, PAYMENT
ORDER BY CU_NAME;

--제일 많이 팔린 상품과 판매금액의 합
SELECT PROD_NAME , TOT 
FROM PRODUCTS F, (SELECT PROD_NO, TOT
                FROM (SELECT PROD_NO, SUM(QUANTITY) TOT
                    FROM SALES
                    GROUP BY PROD_NO)
                    WHERE TOT = (SELECT MAX(TOT)
                                FROM (SELECT PROD_NO, SUM(QUANTITY) TOT
                                FROM SALES
                                GROUP BY PROD_NO))) TEMP
WHERE F.PROD_NO = TEMP.PROD_NO;

--제품별 판매금액이 5억 이상인 제품
SELECT PROD_NAME, TOT
FROM(SELECT PROD_NAME, SUM(AMOUNT) TOT
    FROM PRODUCTS P, SALES S
    WHERE P.PROD_NO = S.PROD_NO
    GROUP BY PROD_NAME) TEMP
WHERE TOT >= 50000000;

--제품의 종류가 가장많은 거래처
SELECT ACC_NAME
FROM (SELECT ACC_NAME, COUNT(*) CNT
FROM ACCOUNTS A, PRODUCTS P
WHERE A.ACC_NO = P.ACC_NO
GROUP BY ACC_NAME)
WHERE CNT = (SELECT MAX(CNT)
              FROM (SELECT ACC_NAME, COUNT(*) CNT
              FROM ACCOUNTS A, PRODUCTS P
              WHERE A.ACC_NO = P.ACC_NO
              GROUP BY ACC_NAME));

--하나도 팔리지 않은 제품
SELECT DISTINCT P.PROD_NO, S.PROD_NO
FROM PRODUCTS P, SALES S
WHERE P.PROD_NO = S.PROD_NO(+) AND S.PROD_NO IS NULL
ORDER BY P.PROD_NO;

SELECT PROD_NAME
FROM PRODUCTS
WHERE PROD_NO IN (SELECT DISTINCT P.PROD_NO
                    FROM PRODUCTS P, SALES S
                    WHERE P.PROD_NO = S.PROD_NO(+)
                    MINUS
                    SELECT DISTINCT P.PROD_NO
                    FROM PRODUCTS P, SALES S
                    WHERE P.PROD_NO = S.PROD_NO);



SELECT * FROM SALES ORDER BY PROD_NO;

DELETE FROM SALES
WHERE PROD_NO IN('30001','30005', '30007');
SELECT PROD_NO
FROM PRODUCTS
ORDER BY PROD_NO;

--하나도 구매하지 않은 고객
SELECT CU_NAME
FROM CUSTOMER C, SALES S
WHERE C.CUST_ID = S.CUST_ID(+)
MINUS
SELECT CU_NAME
FROM CUSTOMER C, SALES S
WHERE C.CUST_ID = S.CUST_ID;

DELETE FROM SALES
WHERE CUST_ID IN ('10001', '10005', '10007');

ROLLBACK;

--구매금액이 5000만원 이상인 고객 명단
SELECT CU_NAME, TOT
FROM CUSTOMER C, (SELECT CUST_ID, SUM(AMOUNT) TOT
                  FROM SALES
                  GROUP BY CUST_ID) TEMP
WHERE TOT >= 50000000 AND C.CUST_ID = TEMP.CUST_ID
ORDER BY TOT DESC;

--가장 많이 팔린 제품 5개 리스트
SELECT ROWNUM, PROD_NO, TOT
FROM (SELECT PROD_NO, SUM(QUANTITY) TOT
      FROM SALES
      GROUP BY PROD_NO
      ORDER BY TOT DESC)
WHERE ROWNUM <= 5;

--1. 카드와 현금 각 총 판매금액
SELECT PAYMENT, SUM(AMOUNT)
FROM SALES
GROUP BY PAYMENT;

--가장 많이 팔린 제품, 가장 적게 팔린 제품

SELECT P.PROD_NO, PROD_NAME
FROM PRODUCTS P, (SELECT PROD_NO,SUM(QUANTITY) TOT
      FROM SALES
      GROUP BY PROD_NO) TEMP
WHERE P.PROD_NO = TEMP.PROD_NO AND TOT = (SELECT MAX(TOT)
             FROM (SELECT PROD_NO,SUM(QUANTITY) TOT
                   FROM SALES
                   GROUP BY PROD_NO));
                   
SELECT P.PROD_NO, PROD_NAME
FROM PRODUCTS P, (SELECT PROD_NO,SUM(QUANTITY) TOT
      FROM SALES
      GROUP BY PROD_NO) TEMP
WHERE P.PROD_NO = TEMP.PROD_NO AND TOT = (SELECT MIN(TOT)
             FROM (SELECT PROD_NO,SUM(QUANTITY) TOT
                   FROM SALES
                   GROUP BY PROD_NO));
                   
--연령별 제품별 판매수량과 금액을 구하시오
SELECT CUST_ID, CU_NAME, TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 1,4)) - TO_NUMBER(SUBSTR(TO_CHAR(BIRTH, 'YYYY-MM-DD'),1,4)) 나이
FROM CUSTOMER;



