SELECT AGE, SUM(QUANTITY), SUM(AMOUNT)
FROM (SELECT TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 1,4)) - TO_NUMBER(SUBSTR(TO_CHAR(BIRTH, 'YYYY-MM-DD'),1,4)) AGE , PROD_NAME, QUANTITY, AMOUNT
      FROM CUSTOMER C, PRODUCTS P, SALES S
      WHERE S.CUST_ID = C.CUST_ID AND S.PROD_NO = P.PROD_NO)
GROUP BY AGE;


--DROP TABLE CUSTOMER;

--데이터 삽입
--INSERT INTO TABLE 데이블명 (컬럼명1, 컬럼명2, 컬럼명3, ....) VALUES(데이터 1, 데이터 2, 데이터 3....);


INSERT INTO CUSTOMER (CUST_ID, CU_NAME,GEN, BIRTH) VALUES ('10016', '이쁜이', 'W', TO_DATE('1998-04-20'));

SELECT * FROM CUSTOMER
WHERE CUST_ID = '10016';

CREATE TABLE  SALE_TEMP(
    ID NUMBER,
    CU_NAME VARCHAR2(30),
    PROD_NAME VARCHAR2(30),
    AMOUNT NUMBER,
    ADDR VARCHAR2(100)
    );

--수정하겠다 저 테이블은 모디파이 저 걸 변경하겠다.
ALTER TABLE SALE_TEMP
MODIFY PROD_NAME VARCHAR2(50);

INSERT INTO SALE_TEMP
SELECT SAL_NO, CU_NAME, PROD_NAME, AMOUNT, ADDR
FROM CUSTOMER C, SALES S, PRODuCTS P
WHERE C.CUST_ID = S.CUST_ID AND S.PROD_NO = P.PROD_NO;

SELECT * FROM SALE_TEMP;

CREATE SEQUENCE NOTE_SEQ  --시퀀스 생성 이름
INCREMENT BY -30 -- 증가 값
START WITH 1 -- 시작 값
MAXVALUE 9999999 -- 최대값
MINVALUE 0 -- 최소값(초기화를 위해 시작 값에 -1
NOCYCLE -- 반복 안함 CYCLE 반복 함
NOCACHE; -- 미리 메모리에 할당안함

ALTER SEQUENCE NOTE_SEQ  --시퀀스 생성 이름
INCREMENT BY 1; -- 증가 값

SELECT NOTE_SEQ.NEXTVAL FROM DUAL;
SELECT NOTE_SEQ.CURRVAL FROM DUAL;



CREATE TABLE TEST1 (
NO NUMBER,
NAME VARCHAR(30)
);

SELECT * FROM TEST1;
INSERT INTO TEST1 VALUES(TEST1_SEQ.NEXTVAL, '꽃사슴');

SELECT * FROM TEST1
ORDER BY NO;
DELETE FROM TEST1;

CREATE TABLE DEPT_EMP
AS
SELECT EMPNO, ENAME, DNAME, HIREDATE, SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
