SELECT * FROM EMP;
UPDATE EMP
SET SAL = SAL *1.03;

ROLLBACK;

-- SAL을 1000미만은 10% 인상, 1000 ~ 1500은 5%인상, 1500초과는 3% 인상
UPDATE EMP
SET SAL = SAL * 1.1
WHERE SAL < 1000;
UPDATE EMP
SET SAL = SAL * 1.05
WHERE SAL BETWEEN 1000 AND 1500;

UPDATE EMP
SET SAL = SAL * 1.03
WHERE SAL > 1500;

-- 두개 이사의 컴럼 수정
--UPDATE 테이블명 
--SET 컬럼명은 = 변경 값, 컬럼명은 = 변경 값,,,,
--WHERE 조건

UPDATE EMP
SET SAL = CASE WHEN SAL < 1000 THEN SAL * 1.1
               WHEN SAL BETWEEN 1000 AND 1500 THEN SAL * 1.05
               WHEN SAL > 1500 THEN SAL * 1.03
               END;
SELECT * FROM EMP
WHERE DEPTNO = 20;

SELECT * FROM EMP;

--부서명이 SALES 이고 SAL이 1500미만인 사원의 부서번호를 40분 부서로 변경

UPDATE EMP
SET DEPTNO = 40
WHERE EMPNO IN(SELECT EMPNO
               FROM EMP E, DEPT D
               WHERE E.DEPTNO = D.DEPTNO AND DNAME = 'SALES' AND SAL < 1500);

CREATE TABLE SAMPLE(
NO NUMBER,
NAME VARCHAR2(20),
ADDRESS VARCHAR2(30),
TEL VARCHAR2(20));

SELECT * FROM SAMPLE;

CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP;

SELECT* FROM EMP;

SELECT * FROM EMP;

UPDATE EMP SET SAL = SAL * 1.1;


