CREATE TABLE EMP AS SELECT * FROM EMPLOYEES;

SELECT * FROM EMP;
DROP TABLE EMP;

CREATE TABLE EMP
AS
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS NAME , SALARY ,DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

DROP TABLE EMP;

CREATE TABLE EMP(EMP_ID, NAME,SAL,DEPR_NAME)
AS
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS NAME , SALARY ,DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM EMP;

ALTER TABLE EMP
ADD HIREDATE DATE;

ALTER TABLE EMP
RENAME COLUMN DEPR_NAME TO DNAME;

ALTER TABLE EMP
MODIFY NAME VARCHAR2(100);

ALTER TABLE EMP
DROP COLUMN HIREDATE;

--ALTER 문으로 참조키 지정 , 삭제
CREATE TABLE TEST(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    AGE NUMBER CHECK(AGE >= 20),
    ADDR VARCHAR2(100) DEFAULT '대전'
);

INSERT INTO TEST(ID,NAME,AGE) VALUES(3,'이쁜이',19);

SELECT * FROM TEST;

ALTER TABLE TEST
DROP CONSTRAINT SYS_C007075;

ALTER TABLE TEST
ADD CONSTRAINT AGE_CHECK CHECK(AGE >=19);

ALTER TABLE TEST
ADD DEPT_ID NUMBER;

UPDATE TEST SET DEPT_ID = 200
WHERE ID = 3;

SELECT * FROM TEST;
SELECT * FROM DEPARTMENTS;
ALTER TABLE TEST
ADD CONSTRAINT DEPT_ID_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE TEST
DROP CONSTRAINT DEPT_ID_FK;

INSERT INTO TEST VALUES(4, 'T송아지',22 ,'광주', 320);

RENAME TEST TO EMP_DEPT;

SELECT * FROM EMP_DEPT;

DELETE FROM EMP_DEPT;
ROLLBACK;
TRUNCATE TABLE EMP_DEPT;

DROP TABLE EMP_DEPT;

CREATE TABLE EMP_HW(
    EMPNO NUMBER,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER,
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER);
    
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);

SELECT * FROM EMP_HW;

ALTER TABLE EMP_HW
MODIFY SAL NUMBER(7,2);

ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;
DELETE FROM EMP_HW;

DROP TABLE EMP_HW;

select * from dict;

select table_name from user_tables;

select owner, table_name from all_tables;

DROP INDEX EMP_NAME_IX;
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%at';

CREATE INDEX EMP_FIRST_NAME_IX
ON EMPLOYEES(FIRST_NAME);

CREATE VIEW EMP30 AS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, HIRE_DATE, LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.DEPARTMENT_ID = 30;

SELECT * FROM EMP30;
DROP VIEW EMP30;

CREATE VIEW FS30 AS
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT ROWNUM, FIRST_NAME, SALARY
FROM FS30
WHERE ROWNUM <= 10;

SELECT ROWNUM, FIRST_NAME,SALARY FROM EMPLOYEES;