SELECT * FROM EMP
WHERE DEPTNO = 20 OR DEPTNO = 30;

SELECT * FROM EMP
WHERE DEPTNO IN(20,30);

SELECT * FROM EMP
WHERE DEPTNO NOT IN(20,30);

-- 부서번호가 20번 부서이며 SAL이 3000 이상
SELECT * FROM EMP
WHERE SAL >= 3000 AND DEPTNO = 20;

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME LIKE '____';

SELECT * FROM EMP
WHERE COMM IS NOT NULL;

SELECT * FROM EMP
INTERSECT
SELECT * FROM EMP
WHERE DEPTNO = 30;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30 AND job = 'SALESMAN';

SELECT * FROM EMP
WHERE DEPTNO IN(20,30) AND SAL > 2000;

SELECT * FROM EMP
WHERE DEPTNO IN(20,30)
UNION
SELECT * FROM EMP
WHERE SAL > 2000;

SELECT * FROM EMP
WHERE SAL >=2000 AND SAL <=3000;

SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' AND SAL NOT BETWEEN 1000 AND 2000 AND DEPTNO = 30;

SELECT EMPNO,ENAME,LENGTH(ENAME), LOWER(ENAME),INITCAP(ENAME), SAL FROM EMP;

create table test(
code varchar2(50),
name varchar2(20),
price number,
amount number,
saledate date);

insert into test values('냉장고-kr-230L','삼성',2300000,1000,sysdate);
insert into test values('김치냉장고-kr-800L','삼성',3300000,1000,sysdate);

select * from test;

SELECT instr(code, '-' ,1), NAME, PRICE FROM TEST;

SELECT SUBSTR(CODE, 1,INSTR(CODE, '-', 1)-1), NAME FROM TEST;

SELECT SUBSTR(CODE, INSTR(CODE, '-', INSTR(CODE, '-',1)+1)+1) 규격, NAME 제조사 FROM TEST;
SELECT INSTR(CODE, '-', INSTR(CODE, '-',1)+1) FROM TEST;

SELECT '801104-1432512', REPLACE('801104-1432512','1432512','*') FROM DUAL;
SELECT REPLACE('801104-1432512', '-', ' ') FROM DUAL;

--SELECT LEFT('801213-2342342',2) FROM DUAL ;

SELECT LPAD('ORACLE', 7,'#') FROM DUAL;
SELECT LPAD('256-2462', 13, '(042)') FROM DUAL;

SELECT RPAD('ORACLE', 7,'#') FROM DUAL;
SELECT RPAD('256-2462', 13, '(042)') FROM DUAL;

SELECT CONCAT(CODE, NAME) FROM TEST;

SELECT TRIM('   TRIM   ') FROM DUAL;

SELECT ROUND(AVG(SAL),2) FROM EMP;
SELECT ROUND(AVG(SAL),10) FROM EMP;

SELECT TRUNC(AVG(SAL),1) FROM EMP;

SELECT CEIL(AVG(SAL)) FROM EMP;

SELECT FLOOR(AVG(SAL)) FROM EMP;
SELECT MOD(-5,3) FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 12) FROM DUAL;

SELECT TO_DATE('1980-02-14') FROM DUAL;

SELECT * FROM TEST
WHERE TO_CHAR(SALEDATE) = TO_DATE('2022-02-04');
SELECT * FROM TEST
WHERE TO_CHAR(SALEDATE, 'YYYY-MM-DD') = '2022-02-04';

SELECT ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('1996-08-06'))) AS 지내온세월 FROM DUAL;

SELECT LAST_DAY(ADD_MONTHS(SYSDATE,24)) FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '화') FROM DUAL;

SELECT EMPNO, ENAME, EMPNO+'500' FROM EMP
WHERE ENAME = 'SCOTT';

SELECT TO_CHAR(EMPNO) FROM EMP;

SELECT  TO_CHAR(EMPNO) || 'ABC', ENAME FROM EMP
WHERE ENAME = 'SCOTT';

SELECT  EMPNO || 1234, ENAME FROM EMP
WHERE ENAME = 'SCOTT';

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD DAY') FROM DUAL;

SELECT 123 + '1234' FROM DUAL;

SELECT * FROM EMP;

SELECT ENAME, NVL(COMM,0) FROM EMP;



