SELECT * FROM EMPLOYEES;
-- SELECT 문 형식
--SELECT (DISTINCT 중복데이터 한번) 테이블명. 컬러명1, 테이블명.컬럼명2.... : 조회할 컬럼들 (* : 모든 컬럼 
--FROM 테이블명1, 테이블명2 ....
--WHERE 조건
--GROUP BY 그룹화할 컬럼명
--HAVING 그룹화 데이터 조회 조건
--ORDER BY (ASC 오름차순/DESC 내림차순) 순서지정 칼럼명

-- SALARY 1000불 이상인 사원의 사원번호, 사원이름, 월급, 부서번호 조회
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >= 10000;


-- 부서번호별 인원수 조회
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--부서번호별 인원수가 10명이상인 부서만 조회
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >= 10
ORDER BY DEPARTMENT_ID;

SELECT * FROM EMPLOYEES, DEPARTMENTS
WHERE employees.department_id= departments.department_id;


SELECT DISTINCT  DEPARTMENT_ID, DEPARTMENT_ID
FROM EMPLOYEES;

--별칭

SELECT EMPLOYEE_ID AS 번호, FIRST_NAME AS 이름, SALARY AS 월급, SALARY*12 AS 연봉
FROM EMPLOYEES;


SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE employees.department_id= departments.department_id;

SELECT EMPLOYEE_ID, FIRST_NAME, D.DEPARTMENT_ID, DEPARTMENT_NAME 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.department_id= D.department_id;

--문자열 더할때는 || OR연산자를 사용
SELECT FIRST_NAME || ' '  || LAST_NAME "이 름"
FROM EMPLOYEES;

--사원의 이름과 월급을 월급이 많은 순으로 조회
SELECT FIRST_NAME || ' '  || LAST_NAME "이름", SALARY 월급
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC, SALARY ASC;