SELECT EMPLOYEE_ID , FIRST_NAME, D.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--부서번호가 DEPARTMENT 30,50,60 이면서 SALARY 10000이상인 사원의 사원번호,이름,
-- 부서명, SALARY, 입사일, 근무도시 조회

SELECT EMPLOYEE_ID 사원번호, FIRST_NAME || ' ' || LAST_NAME 이름, DEPARTMENT_NAME 부서명, SALARY 월급, TO_CHAR(HIRE_DATE,'YYYY-MM-DD') 입사일
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.DEPARTMENT_ID IN(30,50,60);

SELECT EMPLOYEE_ID 사원번호, FIRST_NAME || ' ' || LAST_NAME 이름, DEPARTMENT_NAME 부서명, SALARY 월급, TO_CHAR(HIRE_DATE,'YYYY-MM-DD') 입사일, CITY 근무도시
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND E.DEPARTMENT_ID IN(30,50,60);

-- 부서명 급여정보
SELECT E.EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME 이름, D.DEPARTMENT_NAME 부서명, SALARY
FROM EMPLOYEES E, DEPARTMENTS D, REGIONS R, COUNTRIES C, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID = C.COUNTRY_ID AND C.REGION_ID = R.REGION_ID AND C.REGION_ID = 1;

--JOB_HISTORY에 있는 사원들을 표시하고, CITY, 어떤 지역에서 근무를 했는지 SQL문을 작성하시오
--JOB_HISTORY 전체 출력 + CITY + REGION_NAME 출력 SQL


SELECT J_S.EMPLOYEE_ID, START_DATE, END_DATE, J_S.JOB_ID, J_S.DEPARTMENT_ID, CITY, REGION_NAME
FROM JOB_HISTORY J_S, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE J_S.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID = C.COUNTRY_ID AND C.REGION_ID = R.REGION_ID;

--급여 6000 미만의 집주소를 구하는 SQL

SELECT EMPLOYEE_ID 사원번호, FIRST_NAME || ' ' || LAST_NAME 이름, STREET_ADDRESS 집주소
FROM EMPLOYEES E,  DEPARTMENTS D,LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND SALARY < 6000;
