CREATE TABLE BOARD(
    BNO NUMBER PRIMARY KEY, --글번호
    TITLE VARCHAR2(100), --제목
    WR_NAME VARCHAR2(30), --작성자
    WR_DATE DATE, --작성일
    NOTE VARCHAR2(1000), --작성내용
    SEL_CNT NUMBER -- 조회수
);

CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 99999999
NOCYCLE
NOCACHE;

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '집에가고싶다면 무엇을 해야 하는가?','강동호',SYSDATE,'DB, 글작성 만들고 해야한다',0);

SELECT * FROM BOARD;

CREATE SYNONYM C FOR CUSTOMER;
DROP SYNONYM C;
SELECT * FROM C;

ALTER TABLE BOARD
DROP CONSTRAINT SEL_CNT_NL;
ALTER TABLE BOARD
MODIFY(TITLE CONSTRAINT TITLE_UQ UNIQUE);

DELETE FROM BOARD;

ALTER TABLE BOARD
ADD CONSTRAINT SEL_CNT_NL CHECK(SEL_CNT >= 0);

CREATE TABLE COMMENTS(
    COMM_NO NUMBER PRIMARY KEY,
    COMM_TEXT VARCHAR2(1000),
    BNO NUMBER
);

DROP TABLE COMMENTS;

ALTER TABLE COMMENTS
ADD CONSTRAINT BNO_FK FOREIGN KEY (BNO) REFERENCES BOARD(BNO)
ON DELETE CASCADE;

ALTER TABLE COMMENTS
DROP CONSTRAINT BNO_FK;


INSERT INTO COMMENTS VALUES(1, '호호호호호호호!!!!!', 5);

DELETE FROM BOARD 
WHERE BNO = 5 ;

ALTER TABLE BOARD
MODIFY SEL_CNT DEFAULT 0;
SELECT * FROM BOARD;
INSERT INTO BOARD (BNO,TITLE,WR_NAME, WR_DATE, NOTE) VALUES(1,'AAAA','ABC',SYSDATE,'내용');


CREATE TABLE DEPT_CONST(
    DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY ,
    DNAME VARCHAR(15) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC VARCHAR(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL);
    
CREATE TABLE EMP_CONST(
    EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB VARCHAR(9),
    TEL VARCHAR(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    SAL NUMBER(7 ,2) CHECK(1000 > SAL AND SAL > 9999),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO REFERENCES DEPT_CONST(DEPTNO));
    
ALTER TABLE EMP_CONST
ADD CONSTRAINT EMPCONST_SAL_CHK CHECK(1000 > SAL AND SAL < 9999);

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS;

CREATE USER JSP IDENTIFIED BY 12345;







